language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aleh/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true aleh/react-test npm test

after_success:
  - docker build -t alehhileuski/multi-client ./client
  - docker build -t alehhileuski/multi-nginx ./nginx
  - docker build -t alehhileuski/multi-server ./server
  - docker build -t alehhileuski/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push alehhileuski/multi-client
  - docker push alehhileuski/multi-nginx
  - docker push alehhileuski/multi-server
  - docker push alehhileuski/multi-worker